In [123]:
import pandas as pd

users = pd.DataFrame([
    [1, 'Alice', 'female', '23', 'China ', '2023-01-15'],
    [2, 'Bob', 'male', '31', 'USA', '2023-03-20'],
    [3, 'Cathy', 'female', None, 'china', '2023-02-11'],
    [4, 'David', 'male', '27', 'UK', '2023-05-09'],
    [5, 'Eva', 'female', '35', 'USA ', '2023-04-01'],
    [6, 'Frank', 'male', '19', None, '2023-06-18'],
], columns=['user_id', 'name', 'gender', 'age', 'country', 'signup_date'])


products = pd.DataFrame([
    [101, 'Keyboard', 'Electronics', '199'],
    [102, 'Mouse', 'Electronics', '99'],
    [103, 'Monitor', 'Electronics', '1299'],
    [104, 'Desk', 'Furniture', '899'],
    [105, 'Chair', 'Furniture', '499'],
    [106, 'Notebook', 'Stationery', '15'],
], columns=['product_id', 'product_name', 'category', 'price'])


orders = pd.DataFrame([
    [1001, 1, 101, '2', '2024-01-03 10:15', 'paid', '0'],
    [1002, 2, 103, '1', '2024-01-05 14:20', 'paid', '100'],
    [1003, 1, 106, '5', '2024-01-08 09:00', 'paid', None],
    [1004, 3, 102, '3', '2024-01-08 21:10', 'cancelled', '0'],
    [1005, 4, 104, '1', '2024-02-01 11:30', 'paid', '50'],
    [1006, 5, 105, '2', '2024-02-03 16:45', 'paid', '0'],
    [1007, 2, 101, '1', '2024-02-10 08:00', 'refunded', '0'],
    [1008, 6, 106, '10', '2024-02-12 19:20', 'paid', '5'],
    [1009, 1, 103, '1', '2024-02-15 13:00', 'paid', '200'],
    [1010, 3, 105, '1', '2024-03-01 10:10', 'paid', None],
    [1011, 5, 101, '2', '2024-03-03 12:00', 'paid', '20'],
    [1012, 2, 104, '1', '2024-03-05 18:30', 'paid', '0'],
    [1013, 2, 104, '1', '2024-03-05 18:30', 'paid', '0'],   # 故意重复
], columns=['order_id', 'user_id', 'product_id', 'quantity', 'order_time', 'status', 'discount'])

In [124]:
users.head(3)

   user_id   name  gender  age country signup_date
0        1  Alice  female   23  China   2023-01-15
1        2    Bob    male   31     USA  2023-03-20
2        3  Cathy  female  NaN   china  2023-02-11

In [125]:
users.shape

(6, 6)

In [126]:
users.dtypes

user_id        int64
name             str
gender           str
age              str
country          str
signup_date      str
dtype: object

In [127]:
users.isna().sum().sum()

np.int64(2)

In [128]:
filt = users['country'].notna() & (users['country'] != users['country'].str.strip().str.title())
users[filt]

   user_id   name  gender  age country signup_date
0        1  Alice  female   23  China   2023-01-15
1        2    Bob    male   31     USA  2023-03-20
2        3  Cathy  female  NaN   china  2023-02-11
3        4  David    male   27      UK  2023-05-09
4        5    Eva  female   35    USA   2023-04-01

In [129]:
filt = users['age'].str.isdigit().fillna(False)
users[~filt]

   user_id   name  gender  age country signup_date
2        3  Cathy  female  NaN   china  2023-02-11

In [130]:
filt = (orders['quantity'].str.isdigit().fillna(False)) & (orders['discount'].str.isdigit().fillna(False))
orders[~filt]

   order_id  user_id  product_id quantity        order_time status discount
2      1003        1         106        5  2024-01-08 09:00   paid      NaN
9      1010        3         105        1  2024-03-01 10:10   paid      NaN

In [131]:
filt = orders.duplicated(
    subset = ['user_id', 'product_id', 'quantity', 'order_time', 'status', 'discount'],
    keep = False
)
orders[filt]

    order_id  user_id  product_id quantity        order_time status discount
11      1012        2         104        1  2024-03-05 18:30   paid        0
12      1013        2         104        1  2024-03-05 18:30   paid        0

In [132]:
users['country'] = users['country'].str.strip().str.title()
users

   user_id   name  gender  age country signup_date
0        1  Alice  female   23   China  2023-01-15
1        2    Bob    male   31     Usa  2023-03-20
2        3  Cathy  female  NaN   China  2023-02-11
3        4  David    male   27      Uk  2023-05-09
4        5    Eva  female   35     Usa  2023-04-01
5        6  Frank    male   19     NaN  2023-06-18

In [133]:
users['age'] = users['age'].astype(float)
users

   user_id   name  gender   age country signup_date
0        1  Alice  female  23.0   China  2023-01-15
1        2    Bob    male  31.0     Usa  2023-03-20
2        3  Cathy  female   NaN   China  2023-02-11
3        4  David    male  27.0      Uk  2023-05-09
4        5    Eva  female  35.0     Usa  2023-04-01
5        6  Frank    male  19.0     NaN  2023-06-18

In [134]:
users['signup_date'] = pd.to_datetime(users['signup_date'])
users

   user_id   name  gender   age country signup_date
0        1  Alice  female  23.0   China  2023-01-15
1        2    Bob    male  31.0     Usa  2023-03-20
2        3  Cathy  female   NaN   China  2023-02-11
3        4  David    male  27.0      Uk  2023-05-09
4        5    Eva  female  35.0     Usa  2023-04-01
5        6  Frank    male  19.0     NaN  2023-06-18

In [135]:
orders['quantity'] = orders['quantity'].astype(float)
orders['discount'] = orders['discount'].astype(float)

In [136]:
orders['order_time'] = pd.to_datetime(orders['order_time'])
orders

,order_id,user_id,product_id,quantity,order_time,status,discount
0,1001,1,101,2.0,2024-01-03 10:15:00,paid,0.0
1,1002,2,103,1.0,2024-01-05 14:20:00,paid,100.0
2,1003,1,106,5.0,2024-01-08 09:00:00,paid,NaN
3,1004,3,102,3.0,2024-01-08 21:10:00,cancelled,0.0
4,1005,4,104,1.0,2024-02-01 11:30:00,paid,50.0
5,1006,5,105,2.0,2024-02-03 16:45:00,paid,0.0
6,1007,2,101,1.0,2024-02-10 08:00:00,refunded,0.0
7,1008,6,106,10.0,2024-02-12 19:20:00,paid,5.0
8,1009,1,103,1.0,2024-02-15 13:00:00,paid,200.0
9,1010,3,105,1.0,2024-03-01 10:10:00,paid,NaN
10,1011,5,101,2.0,2024-03-03 12:00:00,paid,20.0
11,1012,2,104,1.0,2024-03-05 18:30:00,paid,0.0
12,1013,2,104,1.0,2024-03-05 18:30:00,paid,0.0

In [137]:
orders = orders.drop_duplicates(
    subset = ['user_id', 'product_id', 'quantity', 'order_time', 'status', 'discount'],
    keep = 'first'    
)

In [138]:
orders['discount'] = orders['discount'].fillna(0)
orders

,order_id,user_id,product_id,quantity,order_time,status,discount
0,1001,1,101,2.0,2024-01-03 10:15:00,paid,0.0
1,1002,2,103,1.0,2024-01-05 14:20:00,paid,100.0
2,1003,1,106,5.0,2024-01-08 09:00:00,paid,0.0
3,1004,3,102,3.0,2024-01-08 21:10:00,cancelled,0.0
4,1005,4,104,1.0,2024-02-01 11:30:00,paid,50.0
5,1006,5,105,2.0,2024-02-03 16:45:00,paid,0.0
6,1007,2,101,1.0,2024-02-10 08:00:00,refunded,0.0
7,1008,6,106,10.0,2024-02-12 19:20:00,paid,5.0
8,1009,1,103,1.0,2024-02-15 13:00:00,paid,200.0
9,1010,3,105,1.0,2024-03-01 10:10:00,paid,0.0
10,1011,5,101,2.0,2024-03-03 12:00:00,paid,20.0
11,1012,2,104,1.0,2024-03-05 18:30:00,paid,0.0

In [140]:
filt = users['country'] == 'China'
users[filt]

   user_id   name  gender   age country signup_date
0        1  Alice  female  23.0   China  2023-01-15
2        3  Cathy  female   NaN   China  2023-02-11

In [144]:
filt = (users['age'] > 25) & (users['gender'] == 'female')
users[filt]

   user_id name  gender   age country signup_date
4        5  Eva  female  35.0     Usa  2023-04-01

In [149]:
filt = (orders['status'] == 'paid')
orders[filt]

,order_id,user_id,product_id,quantity,order_time,status,discount
0,1001,1,101,2.0,2024-01-03 10:15:00,paid,0.0
1,1002,2,103,1.0,2024-01-05 14:20:00,paid,100.0
2,1003,1,106,5.0,2024-01-08 09:00:00,paid,0.0
4,1005,4,104,1.0,2024-02-01 11:30:00,paid,50.0
5,1006,5,105,2.0,2024-02-03 16:45:00,paid,0.0
7,1008,6,106,10.0,2024-02-12 19:20:00,paid,5.0
8,1009,1,103,1.0,2024-02-15 13:00:00,paid,200.0
9,1010,3,105,1.0,2024-03-01 10:10:00,paid,0.0
10,1011,5,101,2.0,2024-03-03 12:00:00,paid,20.0
11,1012,2,104,1.0,2024-03-05 18:30:00,paid,0.0

In [169]:
# filt = orders['order_time'].dt.month == 2
# orders[filt]
filt = (orders['order_time'] >= '2024-02-01') & (orders['order_time'] < '2024-03-01')
orders[filt]

,order_id,user_id,product_id,quantity,order_time,status,discount
4,1005,4,104,1.0,2024-02-01 11:30:00,paid,50.0
5,1006,5,105,2.0,2024-02-03 16:45:00,paid,0.0
6,1007,2,101,1.0,2024-02-10 08:00:00,refunded,0.0
7,1008,6,106,10.0,2024-02-12 19:20:00,paid,5.0
8,1009,1,103,1.0,2024-02-15 13:00:00,paid,200.0

In [177]:
orders['month'] = orders['order_time'].dt.strftime('%Y') + '-' + orders['order_time'].dt.strftime('%m')
orders

,order_id,user_id,product_id,quantity,order_time,status,discount,month
0,1001,1,101,2.0,2024-01-03 10:15:00,paid,0.0,2024-01
1,1002,2,103,1.0,2024-01-05 14:20:00,paid,100.0,2024-01
2,1003,1,106,5.0,2024-01-08 09:00:00,paid,0.0,2024-01
3,1004,3,102,3.0,2024-01-08 21:10:00,cancelled,0.0,2024-01
4,1005,4,104,1.0,2024-02-01 11:30:00,paid,50.0,2024-02
5,1006,5,105,2.0,2024-02-03 16:45:00,paid,0.0,2024-02
6,1007,2,101,1.0,2024-02-10 08:00:00,refunded,0.0,2024-02
7,1008,6,106,10.0,2024-02-12 19:20:00,paid,5.0,2024-02
8,1009,1,103,1.0,2024-02-15 13:00:00,paid,200.0,2024-02
9,1010,3,105,1.0,2024-03-01 10:10:00,paid,0.0,2024-03
10,1011,5,101,2.0,2024-03-03 12:00:00,paid,20.0,2024-03
11,1012,2,104,1.0,2024-03-05 18:30:00,paid,0.0,2024-03

In [180]:
orders['hour'] = orders['order_time'].dt.strftime('%H')
orders

,order_id,user_id,product_id,quantity,order_time,status,discount,month,hour
0,1001,1,101,2.0,2024-01-03 10:15:00,paid,0.0,2024-01,10
1,1002,2,103,1.0,2024-01-05 14:20:00,paid,100.0,2024-01,14
2,1003,1,106,5.0,2024-01-08 09:00:00,paid,0.0,2024-01,09
3,1004,3,102,3.0,2024-01-08 21:10:00,cancelled,0.0,2024-01,21
4,1005,4,104,1.0,2024-02-01 11:30:00,paid,50.0,2024-02,11
5,1006,5,105,2.0,2024-02-03 16:45:00,paid,0.0,2024-02,16
6,1007,2,101,1.0,2024-02-10 08:00:00,refunded,0.0,2024-02,08
7,1008,6,106,10.0,2024-02-12 19:20:00,paid,5.0,2024-02,19
8,1009,1,103,1.0,2024-02-15 13:00:00,paid,200.0,2024-02,13
9,1010,3,105,1.0,2024-03-01 10:10:00,paid,0.0,2024-03,10
10,1011,5,101,2.0,2024-03-03 12:00:00,paid,20.0,2024-03,12
11,1012,2,104,1.0,2024-03-05 18:30:00,paid,0.0,2024-03,18

In [187]:
orders['is_weekend'] = orders['order_time'].dt.dayofweek > 5
orders

,order_id,user_id,product_id,quantity,order_time,status,discount,month,hour,is_weekend
0,1001,1,101,2.0,2024-01-03 10:15:00,paid,0.0,2024-01,10,False
1,1002,2,103,1.0,2024-01-05 14:20:00,paid,100.0,2024-01,14,False
2,1003,1,106,5.0,2024-01-08 09:00:00,paid,0.0,2024-01,09,False
3,1004,3,102,3.0,2024-01-08 21:10:00,cancelled,0.0,2024-01,21,False
4,1005,4,104,1.0,2024-02-01 11:30:00,paid,50.0,2024-02,11,False
5,1006,5,105,2.0,2024-02-03 16:45:00,paid,0.0,2024-02,16,False
6,1007,2,101,1.0,2024-02-10 08:00:00,refunded,0.0,2024-02,08,False
7,1008,6,106,10.0,2024-02-12 19:20:00,paid,5.0,2024-02,19,False
8,1009,1,103,1.0,2024-02-15 13:00:00,paid,200.0,2024-02,13,False
9,1010,3,105,1.0,2024-03-01 10:10:00,paid,0.0,2024-03,10,False
10,1011,5,101,2.0,2024-03-03 12:00:00,paid,20.0,2024-03,12,True
11,1012,2,104,1.0,2024-03-05 18:30:00,paid,0.0,2024-03,18,False

In [201]:
orders['final_amount'] = products.loc[orders['product_id'], 'price'] * orders['quantity'] - orders['discount']

KeyError: "None of [Index([101, 103, 106, 102, 104, 105, 101, 106, 103, 105, 101, 104], dtype='int64')] are in the [index]"